package com.model;


/**
 * TKefang generated by MyEclipse Persistence Tools
 */

public class TKefang implements java.io.Serializable
{

	private Integer id;
	private Integer mendianId;
	private String kefangleixing;
	private String fangjianhao;
	
	private String area;
	private String jieshao;
	private String fujian;
	private Integer qianshu;
	
	private String zhuangtai;//空闲，已预订，已入住
	private String del;
	
	
	public String getArea()
	{
		return area;
	}
	public void setArea(String area)
	{
		this.area = area;
	}
	public String getDel()
	{
		return del;
	}
	public void setDel(String del)
	{
		this.del = del;
	}
	public String getFangjianhao()
	{
		return fangjianhao;
	}
	public void setFangjianhao(String fangjianhao)
	{
		this.fangjianhao = fangjianhao;
	}
	public String getFujian()
	{
		return fujian;
	}
	public void setFujian(String fujian)
	{
		this.fujian = fujian;
	}
	
	public String getZhuangtai()
	{
		return zhuangtai;
	}
	public void setZhuangtai(String zhuangtai)
	{
		this.zhuangtai = zhuangtai;
	}
	public Integer getId()
	{
		return id;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}
	
	public String getKefangleixing()
	{
		return kefangleixing;
	}
	public void setKefangleixing(String kefangleixing)
	{
		this.kefangleixing = kefangleixing;
	}
	public String getJieshao()
	{
		return jieshao;
	}
	public void setJieshao(String jieshao)
	{
		this.jieshao = jieshao;
	}
	public Integer getMendianId()
	{
		return mendianId;
	}
	public void setMendianId(Integer mendianId)
	{
		this.mendianId = mendianId;
	}
	public Integer getQianshu()
	{
		return qianshu;
	}
	public void setQianshu(Integer qianshu)
	{
		this.qianshu = qianshu;
	}

}