package com.model;

/**
 * TMendian generated by MyEclipse Persistence Tools
 */

public class TMendian implements java.io.Serializable
{

	private Integer id;
	private String sheng;
	private String shi;
	private String mingcheng;

	private String dizhi;
	private String dianhua;
	private String jianjie;
	private String xingming;

	private String loginname;
	private String loginpw;
	private String del;


	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public String getSheng()
	{
		return this.sheng;
	}

	public void setSheng(String sheng)
	{
		this.sheng = sheng;
	}

	public String getShi()
	{
		return this.shi;
	}

	public void setShi(String shi)
	{
		this.shi = shi;
	}

	public String getMingcheng()
	{
		return this.mingcheng;
	}

	public void setMingcheng(String mingcheng)
	{
		this.mingcheng = mingcheng;
	}

	public String getDel()
	{
		return del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

	public String getDizhi()
	{
		return this.dizhi;
	}

	public void setDizhi(String dizhi)
	{
		this.dizhi = dizhi;
	}

	public String getDianhua()
	{
		return this.dianhua;
	}

	public void setDianhua(String dianhua)
	{
		this.dianhua = dianhua;
	}

	public String getJianjie()
	{
		return this.jianjie;
	}

	public void setJianjie(String jianjie)
	{
		this.jianjie = jianjie;
	}

	public String getXingming()
	{
		return this.xingming;
	}

	public void setXingming(String xingming)
	{
		this.xingming = xingming;
	}

	public String getLoginname()
	{
		return this.loginname;
	}

	public void setLoginname(String loginname)
	{
		this.loginname = loginname;
	}

	public String getLoginpw()
	{
		return this.loginpw;
	}

	public void setLoginpw(String loginpw)
	{
		this.loginpw = loginpw;
	}

}