package com.model;

/**
 * TRuzhu generated by MyEclipse Persistence Tools
 */

public class TRuzhu implements java.io.Serializable
{

	private Integer id;
	private Integer userId;
	private Integer kefangId;
	private Integer mendianId;

	private String dengjixingming;
	private String shenfenzheng;
	private String ruzhushijian;
	private String tuifangshijian;
	
	private Integer zongfeiyong;
	private TKefang kefang;
	
	
	public Integer getId()
	{
		return id;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}
	public Integer getKefangId()
	{
		return kefangId;
	}
	public void setKefangId(Integer kefangId)
	{
		this.kefangId = kefangId;
	}
	public Integer getMendianId()
	{
		return mendianId;
	}
	public void setMendianId(Integer mendianId)
	{
		this.mendianId = mendianId;
	}
	
	public String getDengjixingming()
	{
		return dengjixingming;
	}
	public void setDengjixingming(String dengjixingming)
	{
		this.dengjixingming = dengjixingming;
	}
	
	public TKefang getKefang()
	{
		return kefang;
	}
	public void setKefang(TKefang kefang)
	{
		this.kefang = kefang;
	}
	public String getRuzhushijian()
	{
		return ruzhushijian;
	}
	public void setRuzhushijian(String ruzhushijian)
	{
		this.ruzhushijian = ruzhushijian;
	}
	public String getShenfenzheng()
	{
		return shenfenzheng;
	}
	public void setShenfenzheng(String shenfenzheng)
	{
		this.shenfenzheng = shenfenzheng;
	}
	public String getTuifangshijian()
	{
		return tuifangshijian;
	}
	public void setTuifangshijian(String tuifangshijian)
	{
		this.tuifangshijian = tuifangshijian;
	}
	public Integer getUserId()
	{
		return userId;
	}
	public void setUserId(Integer userId)
	{
		this.userId = userId;
	}
	public Integer getZongfeiyong()
	{
		return zongfeiyong;
	}
	public void setZongfeiyong(Integer zongfeiyong)
	{
		this.zongfeiyong = zongfeiyong;
	}

}