package com.model;

/**
 * TYuding generated by MyEclipse Persistence Tools
 */

public class TYuding implements java.io.Serializable
{

	private Integer id;
	private Integer userId;
	private Integer kefangId;
	private Integer mendianId;
	
	private String ruzhushiian;
	private String lidianshiian;
	private String yudingzheTel;
	private String yudingshijian;
	
	private TKefang kefang;
	
	
	public Integer getId()
	{
		return id;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}
	public Integer getKefangId()
	{
		return kefangId;
	}
	public void setKefangId(Integer kefangId)
	{
		this.kefangId = kefangId;
	}
	public String getLidianshiian()
	{
		return lidianshiian;
	}
	public void setLidianshiian(String lidianshiian)
	{
		this.lidianshiian = lidianshiian;
	}
	public Integer getMendianId()
	{
		return mendianId;
	}
	public void setMendianId(Integer mendianId)
	{
		this.mendianId = mendianId;
	}
	public String getRuzhushiian()
	{
		return ruzhushiian;
	}
	public void setRuzhushiian(String ruzhushiian)
	{
		this.ruzhushiian = ruzhushiian;
	}
	public String getYudingzheTel()
	{
		return yudingzheTel;
	}
	
	public TKefang getKefang()
	{
		return kefang;
	}
	public void setKefang(TKefang kefang)
	{
		this.kefang = kefang;
	}
	public String getYudingshijian()
	{
		return yudingshijian;
	}
	public void setYudingshijian(String yudingshijian)
	{
		this.yudingshijian = yudingshijian;
	}
	public void setYudingzheTel(String yudingzheTel)
	{
		this.yudingzheTel = yudingzheTel;
	}
	public Integer getUserId()
	{
		return userId;
	}
	public void setUserId(Integer userId)
	{
		this.userId = userId;
	}

}